#archlinux autoswitch-hiveOS Docker
version: "3"
services:
  autoswitch-hiveos:
    restart: always
    build: .
    build:
      context: ./archlinux/
    container_name: autoswitch-hiveOS
    volumes:
      - ./VARS.py:/app/VARS.py:ro
